directories:
  output: dist-electron
  buildResources: build
appId: com.academic.mudtote
productName: MUD & TOTE Diagram Tool
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
extraResources:
  - from: public/icons
    to: icons
win:
  target:
    - target: nsis
      arch:
        - x64
        - ia32
    - target: portable
      arch:
        - x64
mac:
  target:
    target: dmg
    arch:
      - x64
      - arm64
  icon: public/icons/icon.svg
  category: public.app-category.education
linux:
  target:
    - target: AppImage
      arch:
        - x64
    - target: deb
      arch:
        - x64
  icon: public/icons/icon.svg
  category: Education
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 37.2.5
